package com.sample.bean;

public class RealdataBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realdata.realdata_no
     *
     * @mbggenerated
     */
    private String realdataNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realdata.tenant_no
     *
     * @mbggenerated
     */
    private String tenantNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realdata.enterprise
     *
     * @mbggenerated
     */
    private String enterprise;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column realdata.block
     *
     * @mbggenerated
     */
    private String block;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realdata.realdata_no
     *
     * @return the value of realdata.realdata_no
     *
     * @mbggenerated
     */
    public String getRealdataNo() {
        return realdataNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realdata.realdata_no
     *
     * @param realdataNo the value for realdata.realdata_no
     *
     * @mbggenerated
     */
    public void setRealdataNo(String realdataNo) {
        this.realdataNo = realdataNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realdata.tenant_no
     *
     * @return the value of realdata.tenant_no
     *
     * @mbggenerated
     */
    public String getTenantNo() {
        return tenantNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realdata.tenant_no
     *
     * @param tenantNo the value for realdata.tenant_no
     *
     * @mbggenerated
     */
    public void setTenantNo(String tenantNo) {
        this.tenantNo = tenantNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realdata.enterprise
     *
     * @return the value of realdata.enterprise
     *
     * @mbggenerated
     */
    public String getEnterprise() {
        return enterprise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realdata.enterprise
     *
     * @param enterprise the value for realdata.enterprise
     *
     * @mbggenerated
     */
    public void setEnterprise(String enterprise) {
        this.enterprise = enterprise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column realdata.block
     *
     * @return the value of realdata.block
     *
     * @mbggenerated
     */
    public String getBlock() {
        return block;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column realdata.block
     *
     * @param block the value for realdata.block
     *
     * @mbggenerated
     */
    public void setBlock(String block) {
        this.block = block;
    }
}