package com.sample.dal.service;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.sample.dal.model.Administration;
import com.sample.dal.model.AdministrationExample;

public interface AdministrationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administration
     *
     * @mbggenerated
     */
    int countByExample(AdministrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administration
     *
     * @mbggenerated
     */
    int deleteByExample(AdministrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administration
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String tableno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administration
     *
     * @mbggenerated
     */
    int insert(Administration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administration
     *
     * @mbggenerated
     */
    int insertSelective(Administration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administration
     *
     * @mbggenerated
     */
    List<Administration> selectByExample(AdministrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administration
     *
     * @mbggenerated
     */
    Administration selectByPrimaryKey(String tableno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administration
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Administration record, @Param("example") AdministrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administration
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Administration record, @Param("example") AdministrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administration
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Administration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administration
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Administration record);
    
    List<Map<String, Object>> selectByMap(Map<String, Object> map);
    
    int addFiled(Map<String, Object> map);
}