package com.sample.dal.service;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.sample.dal.model.Realdata;
import com.sample.dal.model.RealdataExample;

public interface RealdataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realdata
     *
     * @mbggenerated
     */
    int countByExample(RealdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realdata
     *
     * @mbggenerated
     */
    int deleteByExample(RealdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realdata
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String realdataNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realdata
     *
     * @mbggenerated
     */
    int insert(Realdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realdata
     *
     * @mbggenerated
     */
    int insertSelective(Realdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realdata
     *
     * @mbggenerated
     */
    List<Realdata> selectByExample(RealdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realdata
     *
     * @mbggenerated
     */
    Realdata selectByPrimaryKey(String realdataNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realdata
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Realdata record, @Param("example") RealdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realdata
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Realdata record, @Param("example") RealdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realdata
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Realdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table realdata
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Realdata record);
    
    
    List<Map<String, Object>> selectByMap(Map<String, Object> map);
    
    int addFiled(Map<String, Object> map);
}