package com.sample.dal.model;

public class Block {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block.block_no
     *
     * @mbggenerated
     */
    private String blockNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block.block_name
     *
     * @mbggenerated
     */
    private String blockName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block.parent_block
     *
     * @mbggenerated
     */
    private String parentBlock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column block.tenant_no
     *
     * @mbggenerated
     */
    private String tenantNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block.block_no
     *
     * @return the value of block.block_no
     *
     * @mbggenerated
     */
    public String getBlockNo() {
        return blockNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block.block_no
     *
     * @param blockNo the value for block.block_no
     *
     * @mbggenerated
     */
    public void setBlockNo(String blockNo) {
        this.blockNo = blockNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block.block_name
     *
     * @return the value of block.block_name
     *
     * @mbggenerated
     */
    public String getBlockName() {
        return blockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block.block_name
     *
     * @param blockName the value for block.block_name
     *
     * @mbggenerated
     */
    public void setBlockName(String blockName) {
        this.blockName = blockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block.parent_block
     *
     * @return the value of block.parent_block
     *
     * @mbggenerated
     */
    public String getParentBlock() {
        return parentBlock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block.parent_block
     *
     * @param parentBlock the value for block.parent_block
     *
     * @mbggenerated
     */
    public void setParentBlock(String parentBlock) {
        this.parentBlock = parentBlock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block.remarks
     *
     * @return the value of block.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block.remarks
     *
     * @param remarks the value for block.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column block.tenant_no
     *
     * @return the value of block.tenant_no
     *
     * @mbggenerated
     */
    public String getTenantNo() {
        return tenantNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column block.tenant_no
     *
     * @param tenantNo the value for block.tenant_no
     *
     * @mbggenerated
     */
    public void setTenantNo(String tenantNo) {
        this.tenantNo = tenantNo;
    }
}