package com.sample.dal.model;

public class DictionaryKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.dictionary_key
     *
     * @mbggenerated
     */
    private Integer dictionaryKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.tenant_no
     *
     * @mbggenerated
     */
    private String tenantNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.dictionary_key
     *
     * @return the value of dictionary.dictionary_key
     *
     * @mbggenerated
     */
    public Integer getDictionaryKey() {
        return dictionaryKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.dictionary_key
     *
     * @param dictionaryKey the value for dictionary.dictionary_key
     *
     * @mbggenerated
     */
    public void setDictionaryKey(Integer dictionaryKey) {
        this.dictionaryKey = dictionaryKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.tenant_no
     *
     * @return the value of dictionary.tenant_no
     *
     * @mbggenerated
     */
    public String getTenantNo() {
        return tenantNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.tenant_no
     *
     * @param tenantNo the value for dictionary.tenant_no
     *
     * @mbggenerated
     */
    public void setTenantNo(String tenantNo) {
        this.tenantNo = tenantNo;
    }
}