package com.sample.dal.model;

public class Enterprise {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.enterprise_no
     *
     * @mbggenerated
     */
    private String enterpriseNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.enterprise_name
     *
     * @mbggenerated
     */
    private String enterpriseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.block_no
     *
     * @mbggenerated
     */
    private String blockNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.tenant_no
     *
     * @mbggenerated
     */
    private String tenantNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.enterprise_no
     *
     * @return the value of enterprise.enterprise_no
     *
     * @mbggenerated
     */
    public String getEnterpriseNo() {
        return enterpriseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.enterprise_no
     *
     * @param enterpriseNo the value for enterprise.enterprise_no
     *
     * @mbggenerated
     */
    public void setEnterpriseNo(String enterpriseNo) {
        this.enterpriseNo = enterpriseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.enterprise_name
     *
     * @return the value of enterprise.enterprise_name
     *
     * @mbggenerated
     */
    public String getEnterpriseName() {
        return enterpriseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.enterprise_name
     *
     * @param enterpriseName the value for enterprise.enterprise_name
     *
     * @mbggenerated
     */
    public void setEnterpriseName(String enterpriseName) {
        this.enterpriseName = enterpriseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.block_no
     *
     * @return the value of enterprise.block_no
     *
     * @mbggenerated
     */
    public String getBlockNo() {
        return blockNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.block_no
     *
     * @param blockNo the value for enterprise.block_no
     *
     * @mbggenerated
     */
    public void setBlockNo(String blockNo) {
        this.blockNo = blockNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.tenant_no
     *
     * @return the value of enterprise.tenant_no
     *
     * @mbggenerated
     */
    public String getTenantNo() {
        return tenantNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.tenant_no
     *
     * @param tenantNo the value for enterprise.tenant_no
     *
     * @mbggenerated
     */
    public void setTenantNo(String tenantNo) {
        this.tenantNo = tenantNo;
    }
}