package com.sample.dal.model;

public class RolePermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.row_id
     *
     * @mbggenerated
     */
    private String rowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.role_id
     *
     * @mbggenerated
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permission.permission_no
     *
     * @mbggenerated
     */
    private String permissionNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.row_id
     *
     * @return the value of role_permission.row_id
     *
     * @mbggenerated
     */
    public String getRowId() {
        return rowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.row_id
     *
     * @param rowId the value for role_permission.row_id
     *
     * @mbggenerated
     */
    public void setRowId(String rowId) {
        this.rowId = rowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.role_id
     *
     * @return the value of role_permission.role_id
     *
     * @mbggenerated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.role_id
     *
     * @param roleId the value for role_permission.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permission.permission_no
     *
     * @return the value of role_permission.permission_no
     *
     * @mbggenerated
     */
    public String getPermissionNo() {
        return permissionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permission.permission_no
     *
     * @param permissionNo the value for role_permission.permission_no
     *
     * @mbggenerated
     */
    public void setPermissionNo(String permissionNo) {
        this.permissionNo = permissionNo;
    }
}